# Generated by Django 4.0.4 on 2022-09-22 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name_plural': 'Technologies',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_created=True, auto_now_add=True, null=True)),
                ('title', models.CharField(max_length=64)),
                ('subtitle', models.CharField(default='-', max_length=128)),
                ('description', models.CharField(max_length=300)),
                ('github_link', models.URLField(blank=True, null=True)),
                ('live_link', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='projects/')),
                ('technologies', models.ManyToManyField(to='portfolio.technology')),
            ],
        ),
    ]
